<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Rebound</AssemblyName>
    <RootNamespace>Rebound</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='Nomad'">
    <Managed>$(GameFolder)\BladeAndSorcery_Data\Managed</Managed>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Nomad'">
    <Managed>$(NomadFolder)\BladeAndSorcery_Data\Managed</Managed>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ThunderRoad">
      <HintPath>$(Managed)\ThunderRoad.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(Managed)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(Managed)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(Managed)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(Managed)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyManifest" AfterTargets="Build">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\manifest.json"
          DestinationFolder="$(OutputPath)"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
